kind: pipeline
name: default

steps:
- name: lint
  image: golang:1.12
  commands:
  - bash -c "if [[ \$(gofmt -l *.go) ]]; then gofmt -l *.go; exit 1; fi"
  - bash -c "if [[ \$(goimports -d *.go) ]]; then goimports -d *.go; exit 1; fi"
  when:
    event:
      - push    
    branch:
      - master  

- name: test
  image: golang:1.12
  commands:
  - go test github.com/Strum355/log -v
  when:
    event:
      - push    
    branch:
      - master    